//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHD_Wifi {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class SavedSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SavedSettings defaultInstance = ((SavedSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SavedSettings())));
        
        public static SavedSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WifiName {
            get {
                return ((string)(this["WifiName"]));
            }
            set {
                this["WifiName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WifiPassword {
            get {
                return ((string)(this["WifiPassword"]));
            }
            set {
                this["WifiPassword"] = value;
            }
        }
    }
}
